[workspace]
members = [
    "crates/seija-app",
    "crates/seija-core",
    "crates/seija-asset",
    "crates/seija-winit",
    "crates/seija-render",
    "crates/seija-transform",
    "crates/seija-gltf",
    "crates/seija-material-compiler",
    "seija-examples"
]