[package]
name = "lib-io-async"
version = "0.1.0"
edition = "2021"

#[lib]
#crate-type = ["cdylib"]

[dependencies]
reqwest = "0.11.16"
tokio = {version = "1.12.0", features = ["full"] }
lazy_static = "1.4.0"
crossbeam-channel = "0.5.8"
bytes = "1.0"