[package]
name = "seija-asset"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy_ecs = "0.5.0"
seija-app = {path = "../seija-app"}
seija-core = {path = "../seija-core"}
uuid = "0.8.2"
rand = "0.8.0"