[package]
name = "seija-render"
version = "0.1.0"
edition = "2018"

[dependencies]
seija-app = {path = "../seija-app"}
seija-core = {path = "../seija-core"}
seija-winit = {path = "../seija-winit"}
seija-transform = {path = "../seija-transform"}
lite-clojure-eval = {git = "https://github.com/seija-engine/lite-clojure.git"}
serde_json = "1.0.64"
uuid = "0.8.2"
bitflags = "1.2.1"
wgpu = "0.9.0"
futures-lite = "1.12.0"
bevy_ecs = "0.5.0"
raw-window-handle = "0.3.3"
thiserror = "1.0.25"
glam = "0.17.1"
num_enum = "0.5.1"