[package]
name = "seija-gltf"
version = "0.1.0"
edition = "2018"


[dependencies]
gltf = "0.16.0"
seija-render = {path = "../seija-render"}
seija-asset = {path = "../seija-asset"}
seija-transform = {path = "../seija-transform"}
glam = "0.17.1"
bevy_ecs = "0.5.0"